# Site settings
title: Effie
tag_text: Biscuit
description: Hello fellow adventurer
# baseurl: "/blog" # the subpath of your site, e.g. /blog
# url: "https://example.com" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
remote_theme: Biscuit
exclude: ["README.md"]
sass:
  style: compressed
